project_id = "rlwbztjdfmndagnenwog"

[functions.ai-simulator]
verify_jwt = false

[functions.integrations]
verify_jwt = false

[functions.twilio-voice-inbound]
verify_jwt = false

[functions.twilio-voice-escalate]
verify_jwt = false

[functions.twilio-voice-voicemail]
verify_jwt = false

[functions.twilio-voice-dial-complete]
verify_jwt = false

[functions.twilio-voice-conversation]
verify_jwt = false

[functions.twilio-send-sms]
verify_jwt = false

[functions.twilio-webhook-test]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.bulk-import-invite]
verify_jwt = false

[functions.get-credentials]
verify_jwt = false
